<?php
class TextformatterUnentities extends Textformatter {
    public static function getModuleInfo() {
        return [
            'title' => 'Textformatter Unentities',
            'version' => 1,
            'summary' => 'Convert HTML entities back to their original characters.',
            'autoload' => true,
            'singular' => true,
            'href' => 'https://github.com/Matoseb/TextformatterUnentities'
        ];
    }

    public function format(&$str) {
        $sanitizer = $this->wire('sanitizer');
        $str = $sanitizer->unentities($str);
    }
}